const { execSync } = require("child_process");
const { readFileSync, writeFileSync } = require("fs");
const { join } = require("path");

const DUMMY_VERSION = "0.0.0";
const ROOT = join(__dirname, "..");

function bumpPatch(ver) {
  const parts = ver.split(".");
  if (parts.length >= 3) {
    const patch = parseInt(parts[2], 10);
    if (!isNaN(patch)) {
      parts[2] = (patch + 1).toString();
      return parts.slice(0, 3).join(".");
    }
  }
  return ver;
}

function getVersion() {
  // 1. Allow explicit override via environment variable or CLI argument
  const envVer = process.env.VERSION;
  if (envVer && envVer !== DUMMY_VERSION) {
    return envVer.replace(/^v/, "");
  }

  const cliArg = process.argv.slice(2).find((arg) => !arg.startsWith("-"));
  if (cliArg) {
    return cliArg.replace(/^v/, "");
  }

  // 2. Dynamic git-based version resolution
  try {
    const tag = execSync("git describe --tags --abbrev=0 2>/dev/null", { encoding: "utf-8" }).trim().replace(/^v/, "");
    const count = execSync(`git rev-list ${tag}..HEAD --count 2>/dev/null`, { encoding: "utf-8" }).trim();
    const status = execSync("git status --porcelain 2>/dev/null", { encoding: "utf-8" }).trim();
    const dirty = status.length > 0;

    if (count === "0" && !dirty) {
      return tag;
    }

    // Dynamic prerelease version for npm compatibility (e.g., 1.0.8-dev.1)
    const nextVer = bumpPatch(tag);
    let dynamicVer = `${nextVer}-dev.${count || 0}`;
    if (dirty) {
      dynamicVer += `.dirty`;
    }
    return dynamicVer;
  } catch {
    const timestamp = Math.floor(Date.now() / 1000);
    return `0.0.0-dev.${timestamp}`;
  }
}

function setPackageVersion(version) {
  const pkgPath = join(ROOT, "package.json");
  const lockPath = join(ROOT, "package-lock.json");

  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  const lock = JSON.parse(readFileSync(lockPath, "utf-8"));

  pkg.version = version;
  lock.version = version;
  if (lock.packages && lock.packages[""]) {
    lock.packages[""].version = version;
  }

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  writeFileSync(lockPath, JSON.stringify(lock, null, 2) + "\n");

  // Also update src/version.ts so compiled code has matching version
  const versionTsPath = join(ROOT, "src", "version.ts");
  const code = `// Auto-generated by scripts/publish.js — do not edit\nexport const VERSION = ${JSON.stringify(version)};\n`;
  writeFileSync(versionTsPath, code);
}

const version = getVersion();
console.log(`Publishing version: ${version}`);

setPackageVersion(version);

// Rebuild project with the updated version.ts before publishing
try {
  execSync("npm run build", { cwd: ROOT, stdio: "inherit" });
} catch (e) {
  console.error("Build failed before publish.");
  process.exit(1);
}

const revert = () => setPackageVersion(DUMMY_VERSION);
process.on("exit", revert);
process.on("SIGINT", () => process.exit(1));
process.on("SIGTERM", () => process.exit(1));

const extraFlags = process.argv.slice(2).filter((arg) => arg.startsWith("-")).join(" ");
const publishCmd = `npm publish --access public --registry https://registry.npmjs.org/ ${extraFlags}`.trim();

try {
  execSync(publishCmd, { stdio: "inherit" });
} catch {
  process.exit(1);
}

