const { execSync } = require("child_process");
const { writeFileSync } = require("fs");
const { join } = require("path");

let version = "0.0.0-dev";
let dirty = false;

try {
  const tag = execSync("git describe --tags --abbrev=0 2>/dev/null", { encoding: "utf-8" }).trim();
  const count = execSync(`git rev-list ${tag}..HEAD --count`, { encoding: "utf-8" }).trim();
  const status = execSync("git status --porcelain 2>/dev/null", { encoding: "utf-8" }).trim();

  dirty = status.length > 0;

  if (count === "0") {
    version = tag;
  } else {
    version = `${tag}+dev.${count}`;
  }
} catch {
  // git not available or no tags — fall back to dev version
}

if (dirty) {
  version += ".dirty";
}

const code = `// Auto-generated by scripts/version.ts — do not edit
export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(join(__dirname, "..", "src", "version.ts"), code);
console.log(`Version: ${version}`);
